import PDFDocument from 'pdfkit';
import type { Response } from 'express';
import type { ItineraryDoc, ItineraryItem } from '../models/Itinerary.js';

const TYPE_LABEL: Record<ItineraryItem['type'], string> = {
  flight: 'Flight',
  hotel: 'Hotel',
  train: 'Train',
  bus: 'Bus',
  cab: 'Cab / Transfer',
  activity: 'Activity',
  meal: 'Meal',
  transfer: 'Transfer',
  note: 'Note',
};

function formatDateRange(start?: string, end?: string): string {
  if (start && end) return `${start} - ${end}`;
  if (start) return start;
  if (end) return end;
  return '';
}

export function streamItineraryPdf(res: Response, itinerary: ItineraryDoc): void {
  const filename = `${itinerary.title.replace(/[^a-z0-9-_ ]/gi, '').replace(/\s+/g, '_')}.pdf`;
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="${filename || 'itinerary.pdf'}"`);

  const doc = new PDFDocument({ size: 'A4', margin: 50 });
  doc.pipe(res);

  doc.fontSize(26).fillColor('#1f2937').text(itinerary.title, { align: 'left' });
  doc.moveDown(0.3);

  const subtitle = [itinerary.destination, formatDateRange(itinerary.startDate, itinerary.endDate)]
    .filter(Boolean)
    .join('  ·  ');
  if (subtitle) {
    doc.fontSize(12).fillColor('#6b7280').text(subtitle);
  }

  if (itinerary.summary) {
    doc.moveDown(0.8);
    doc.fontSize(11).fillColor('#374151').text(itinerary.summary, { align: 'left' });
  }

  doc.moveDown(1);
  doc
    .strokeColor('#e5e7eb')
    .lineWidth(1)
    .moveTo(doc.x, doc.y)
    .lineTo(doc.page.width - doc.page.margins.right, doc.y)
    .stroke();
  doc.moveDown(0.8);

  itinerary.days.forEach((day, dayIdx) => {
    const heading = day.label
      ? day.date
        ? `${day.label} - ${day.date}`
        : day.label
      : day.date ?? `Day ${dayIdx + 1}`;

    if (doc.y > doc.page.height - 150) doc.addPage();

    doc.moveDown(0.5);
    doc.fontSize(16).fillColor('#111827').text(heading);
    doc.moveDown(0.3);

    if (day.items.length === 0) {
      doc.fontSize(10).fillColor('#9ca3af').text('No activities planned.');
      return;
    }

    day.items.forEach((item) => {
      if (doc.y > doc.page.height - 120) doc.addPage();

      const left = doc.x;
      const timePart = item.time ? `${item.time}  ` : '';
      const label = TYPE_LABEL[item.type] ?? 'Item';

      doc
        .fontSize(11)
        .fillColor('#4f46e5')
        .text(`${timePart}${label.toUpperCase()}`, left, doc.y, { continued: false });

      doc.fontSize(12).fillColor('#111827').text(item.title);

      if (item.location) {
        doc.fontSize(10).fillColor('#6b7280').text(item.location);
      }
      if (item.description) {
        doc.fontSize(10).fillColor('#374151').text(item.description);
      }
      if (item.bookingRef) {
        doc.fontSize(9).fillColor('#9ca3af').text(`Confirmation: ${item.bookingRef}`);
      }
      doc.moveDown(0.6);
    });

    doc.moveDown(0.4);
  });

  doc.moveDown(2);
  doc
    .fontSize(8)
    .fillColor('#9ca3af')
    .text('Generated by Wanderlog · AI Itinerary Builder', { align: 'center' });

  doc.end();
}
